name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]
    paths-ignore:
      - "**.md"
      - "LICENSE"

  pull_request:
    branches: ["main"]
    paths-ignore:
      - "**.md"
      - "LICENSE"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Clear:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
          architecture: x64

      - name: Clear
        run: |
          pip install requests
          python scripts/delete_smms_img.py

  CI:
    needs: [Clear]
    strategy:
      matrix:
        python-version: ["3.11"]
        os-version: ["macos-latest", "windows-latest", "ubuntu-20.04"]

    runs-on: ${{ matrix.os-version }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: pdm-project/setup-pdm@v3
        name: Setup PDM
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
          version: 2.11.1
          prerelease: false
          enable-pep582: false
          allow-python-prereleases: false
          update-python: true

      - name: Build
        run: |
          pdm install
          pdm run pyinstaller

      - name: cp-windows
        if: matrix.os-version == 'windows-latest'
        run: |
          cd dist
          7z a -r ptf-${{ matrix.os-version }}.zip ./*

      - name: cp-unix
        if: matrix.os-version != 'windows-latest'
        run: |
          cd dist
          zip -9 -r ptf-${{ matrix.os-version }}.zip ./*

      - name: upload
        uses: actions/upload-artifact@v3
        with:
          name: ptf-${{ matrix.os-version }}
          path: dist/ptf-${{ matrix.os-version }}.zip

      - name: Test
        run: |
          pdm test

      - name: Test Build
        run: |
          python scripts/ci_test_build.py
