name: Test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'
      - 'LICENSE'
    
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'
      - 'LICENSE'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.10'
          architecture: 'x64'
      - name: Install requirements and installer
        run: |
          pip install -r requirements.txt
          pip install pyinstaller
      - name: Run pyinstaller
        run: |
          python __main__.py
          PyInstaller __main__.spec
          xcopy config.yaml dist
          cd dist
          xcopy config.yaml PT-Factory
          cd PT-Factory
          ./PT-Factory
          
  build-X86-Linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Install Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.10'
        architecture: 'x64'
    - name: Install requirements and installer
      run: |
        pip install -r requirements.txt
        pip install pyinstaller
    - name: Run pyinstaller
      run: |
        python __main__.py
        pyinstaller __main__.spec
        cp config.yaml dist
        cd dist
        cp config.yaml PT-Factory
        cd PT-Factory
        ./PT-Factory

  build-MacOS:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.10'
          architecture: 'x64'
      - name: Install requirements and installer
        run: |
          pip install -r requirements.txt
          pip install pyinstaller
      - name: Run pyinstaller
        run: |
          python __main__.py
          pyinstaller __main__.spec
          cp -r config.yaml dist
          cd dist
          cp -r config.yaml PT-Factory
          cd PT-Factory
          ./PT-Factory
